import type { Score } from './types';

export const scores: Score[] = [
  {
    id: 'score-001',
    studentName: 'Krishna Sai',
    taskName: 'Week 1: Foundation & Mindset',
    depth: 10,
    relevance: 9,
    applicability: 9,
    authenticity: 10,
    packaging: 8,
    total: 46,
    scorerName: 'Scorer One',
    date: '2024-08-16T10:00:00Z',
  },
  {
    id: 'score-002',
    studentName: 'Vignesh Nayar',
    taskName: 'Week 1: Foundation & Mindset',
    depth: 8,
    relevance: 9,
    applicability: 8,
    authenticity: 8,
    packaging: 9,
    total: 42,
    scorerName: 'Scorer One',
    date: '2024-08-17T11:30:00Z',
  },
  {
    id: 'score-003',
    studentName: 'Abdullakhan Patan',
    taskName: 'Week 1: Foundation & Mindset',
    depth: 9,
    relevance: 9,
    applicability: 9,
    authenticity: 8,
    packaging: 9,
    total: 44,
    scorerName: 'Scorer One',
    date: '2024-08-17T14:00:00Z',
  },
  {
    id: 'score-004',
    studentName: 'Krishna Sai',
    taskName: 'Week 2: Awareness & Exploration',
    depth: 10,
    relevance: 10,
    applicability: 9,
    authenticity: 9,
    packaging: 10,
    total: 48,
    scorerName: 'Scorer One',
    date: '2024-08-23T09:00:00Z',
  },
];
